services:
  - type: web
    name: travel-planner-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
    rootDirectory: backend
